#Mysql
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
#    username: root
#    password:
#  jpa.hibernate.ddl_auto: update

#Postgre sql
spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/ERP_IIPEV2
    url: jdbc:postgresql://localhost:5432/cloud_vendor?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true

    #    ?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: postgres
    password: root
  jpa:
    default:
      properties:
        hibernate:
          physical_naming_strategy: "io.micronaut.data.hibernate.naming.DefaultPhysicalNamingStrategy"
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  mail:
    host: smtp.gmail.com
    port: 587
    username: komalilaveti.erpi@iipe.ac.in
    password: ksxt urfy gsci rvxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  cors:
    allowed-origins: http://localhost:3000

